Fix AttributeError: 'ClockActivity' object has no attribute '_pathetic'
On OLPC XO-1, if the ticking clock is already enabled, a traceback
occurs;

Traceback (most recent call last):
  File "/home/olpc/Activities/Clock.activity/clock.py", line 467, in _ticking_toggled_cb
    if self._pathetic:
AttributeError: 'ClockActivity' object has no attribute '_pathetic'

Caused by toggling the button before the hardware has been identified.

Move the identification of hardware higher up in the initialisation.